### ISSUE TITLE
ImageProcessor.cpp:25:19: fatal error: mpfit.h: No such file or directory

### ISSUE THREAD

**Issue by rjp350z** [hairu/freelss#1]
Was testing out the software install just now and kept hitting the following error when making 
FREELSS

g++ -c -O3 -Wall -Winvalid-pch -fexceptions -I/usr/local/include -I/opt/vc/incluageProcessor.cpp
ImageProcessor.cpp:25:19: fatal error: mpfit.h: No such file or directory
compilation terminated.
Makefile:45: recipe for target 'ImageProcessor.o' failed
make: **\* [ImageProcessor.o] Error 1

When I look at original ImageProcessor.cpp from src
the include shows as #include <mpfit.h>
I changed to #Include "mpfit.h" 
it compiled just fine

**Comment by hairu** [comment]
Odd, I'll look into it.  The source on Github is a little out of date but
you should still be able to run it fine.  I'll update it when I get a
little breathing room from launching this Kickstarter!

**Comment by rjp350z** [comment]
No problem Hairu - Can 't wait for the April delivery ;)
Also,  Is there a way to change the default 80 Port in the software?  I already have a web server in the house running on that port

**Comment by MacTheApple** [comment]
@rjp350z  line 65 in main.cpp
