### ISSUE TITLE
Errors on scan prevents entry into scan page

### ISSUE THREAD

**Issue by thevisad** [hairu/freelss#11]
If there is an issue with the scan or the scan file, an error is presented on the scan page. When attempting to access the scan page, you are presented with the below error and are unable to proceed. You must manually remove the failed scan from the system in order to access the page. 

ERROR
Error obtaining stats on file: /scans/1434159847.xyz

**Comment by hairu** [comment]
Failed calls to stat() are handled more gracefully now.  What sort of errors were leading to your problem?

**Comment by thevisad** [comment]
I will try with 1.8, but in 1.7 the scans appeared to be proceeding normally and process properly until 100% generating files. The page refreshes and then displays the above error on the scan page. You can manually change the url to access the camera, but the scan page only presents the above error. Once you manually delete the files, the scan page is accessible again.

**Comment by hairu** [comment]
I see from above that you are generating XYZ files.  XYZ files are very large and take a lot of CPU power to generate.  This can result in a fairly long generation process for the Raspberry Pi.  Ensure that you are not running out of disk space on the SD card.  As far as the stat() error I'm guessing that the application was killed while the XYZ file was open or the SD card was filled while it was open.  Can you verify this assumption?  Unless you have a good reason not to, you should use binary PLY, as it is the fastest to generate and contains the point data, face data, and color information in the same file.

**Comment by thevisad** [comment]
I am fairly positive I am not running out of space (11534 free on the setup page) ; however, you are correct the generation time is definitely taking a fair amount of time on the Pi 2 B+.  I can disable the xyz and just use the PLY for now. If the application can handle that error and just present a delete option for the failed file, it might be better in the long run. I am not sure of the skill of all users concerned in accessing the command line. As far as the app being killed, I am unsure, there is nothing in the logs to indicate a failure of any kind.

**Comment by hairu** [comment]
The commit last night should simply display a file size of 0KB when this error occurs and still allow access to the SCAN page and for normal deletion (by clicking the "delete" button next to the scan).
