### ISSUE TITLE
Lockdown?

### ISSUE THREAD

**Issue by avluis** [hairu/freelss#16]
Can we enhance the built-in web server with authentication - a simple password could do if for those that don't want to get too complicated, but still desire to lock down access to the scanner (specially for those that share their network connection in their home).

**Comment by hairu** [comment]
Sounds like a great idea to me.  HTTPS is probably overboard but I can see using HTTP Basic Auth with an SHA hashed password for this situation.  I will get it into the next release if there is enough time.

**Comment by hairu** [comment]
This feature has been implemented as described above in version 1.10.  It can be enabled from the Security page.
