### ISSUE TITLE
Error while loading shared libraries: libmicrohttpd.so.12

### ISSUE THREAD

**Issue by p-hebert** [hairu/freelss#27]
Hi! My pals and I are working on [ATLAS 3D Scanner by Murobo](https://www.thingiverse.com/thing:1280901), and I'm attempting to install and use freelss.

Unfortunately, once installed, when trying to use it through `sudo freelss`, I get the following error: 

```
freelss: error while loading shared libraries: libmicrohttpd.so.12: cannot open shared object file: No such file or directory
```
I verified that libmicrohttpd was installed in /usr/local/lib, and it is;
I also verified that the LD_LIBRARY_PATH was pointing to /usr/local/lib, and it is.

I tried the steps at this [StackOverflow issue](https://stackoverflow.com/questions/480764/linux-error-while-loading-shared-libraries-cannot-open-shared-object-file-no-s#21173918)

Any idea how to overcome this issue?

Cheers :sparkles: :unicorn:

**Comment by parkitny** [comment]
After updating `LD_LIBRARY_PATH`, did you run: `sudo  ldconfig`?

This solved it for me.

**Comment by p-hebert** [comment]
Hi parknity!

It has been a long while, and I cannot say for sure, but I don't think I did.

I'll close this issue given that I don't have any intention to come back to it.

Thanks for your good work & keep it up,

Cheers,

Philippe
