### ISSUE TITLE
Readme.md missing steps and library path

### ISSUE THREAD

**Issue by VikOlliver** [hairu/freelss#3]
I'd suggest that the Readme.md file contains a "cd" at the start of each block of instructions or the naive user may end up at the bottom of a deep directory tree!

Also, as followed, the user will end up with:

./freelss: error while loading shared libraries: libraspicam.so.0.1: cannot open shared object file: No such file or directory

I think the user needs to type "sudo ldconfig" after installing the camera libraries.

**Comment by hairu** [comment]
Done.

**Comment by zhanghaijason** [comment]
thank you!
