### ISSUE TITLE
UpdateManager.cpp appears to require RapidXML

### ISSUE THREAD

**Issue by owens-bill** [hairu/freelss#7]
It appears that UpdateManager.cpp is dependent not only on curl (as mentioned in README.md) but also on RapidXML. I haven't found a packaged version of it for Raspbian yet; does it need to be built from source? Either way, it should be called out as a dependency.

**Comment by phrickelberg** [comment]
works 4 me:
download http://sourceforge.net/projects/rapidxml/files/rapidxml/rapidxml%201.13/ to contrib
and patch Makefile CFLAGS with " -I../contrib/rapidxml-1.13\"

Happy hacking

**Comment by andrew24** [comment]
Hi phrickelberg,
Can you be more specific regarding comments which has to be done that will work.

Thanks

**Comment by phrickelberg** [comment]
Moin moin Andrew24,

i'll try:

1) download http://sourceforge.net/projects/rapidxml/files/rapidxml/rapidxml%201.13/rapidxml-1.13.zip/download to new freelss/contrib folder

$ cd freelss
$ mkdir contrib
$ cd contrib
$ wget http://sourceforge.net/projects/rapidxml/files/rapidxml/rapidxml%201.13/rapidxml-1.13.zip/download
$ unzip download

2 ) patch the makefile
$ cd ../src
$ vi Makefile:
![2015-03-24 21_17_26-192 168 9 127 - putty](https://cloud.githubusercontent.com/assets/10666044/6811862/4fc493c0-d26b-11e4-99cb-09e668b214c9.png)
$ make

HTH

**Comment by hairu** [comment]
I missed that file on the commit.  Try now...
